language: cpp
os:
  - linux
  - osx
  - windows
addons:
  apt:
    packages:
      - cmake-data
      - cmake
      - doxygen
  homebrew:
    packages:
    - cmake
    - doxygen
    update: true
before_install:
  - if [ $TRAVIS_OS_NAME = windows ]; then choco install cmake; choco install doxygen.install; choco install make; refreshenv; fi
script:
- cmake -Bbuild -H.
- make -C build
before_deploy:
- doxygen
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: gh-pages
  local_dir: ./doc/html/
  on:
    branch: master
    condition: $TRAVIS_OS_NAME == linux
